review/musicians/urls.py
from django.urls import path
from . import views

# 어플리케이션 name space
app_name = "musicians"

# 장고 내부적으로 정해진 이름
urlpatterns = [
    # u - v -t 순서 고정
    # path_name을 무엇으로 지었는지, 어떤 view 함수를 실행하는지
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    # django가 지정한 경로 작성 방식
    # <데이터 타입 : 변수 명>
    # 실제 사용자가 작성하는 url
    # '3/'
    path('<int:musician_pk>/', views.detail, name="detail"),
    path('<int:musician_pk>/update/', views.update, name="update"),
    path('<int:musician_pk>/delete/', views.delete, name="delete"),
    path('<int:musician_pk>/album_create/', views.album_create, name="album_create"),

]

review/review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 각 어플리케이션 마다 urls 관리를 위해 분리
    path('musicians/', include('musicians.urls')),
    path('admin/', admin.site.urls),
]

review/musicians/models.py
from django.db import models

# Create your models here.
# 객체 생성(클래스 생성) ->  테이블명
# 모델에서는 모델에 관한 내용만 정리하는 것이 좋다
# form은 forms.py를 새로 만들어서 사용

class Musician(models.Model):
    # 맴버 변수
    # name = '이름이란 사람이 가지는 공통특성'
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return f'{self.name} : {self.age}'

class Album(models.Model):
    # Musican과 1:N 관계
    musician = models.ForeignKey(Musician, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)

    def __str__(self):
        return f'{self.title}'

review/musicians/forms.py
# 장고에서 미리 정의해둔 forms 가져오기
from django import forms
# model에서 정의한 Musician 객체 받아오기
from .models import Musician

# 클래스로 정의
class MusicianForm(forms.ModelForm):
    # 클래스에 대한 클래스
    class Meta:
        # 어떤 모델 ? Musican에 정의된 것
        model = Musician
        # fields = ['name', 'age']
        fields = '__all__'

review/musicians/views.py
from django.shortcuts import render, redirect
from .forms import MusicianForm
from .models import Musician, Album

# Create your views here.
# 함수정의 함수이름(parameter)
def index(request):
    # .all()로 조회하면 querySet형태
    # querySet은 마치 list처럼 사용가능
    musicians = Musician.objects.all()
    context = {
        'musicians': musicians
    }
    return render(request, 'musicians/index.html', context)

def create(request):
    if request.method == "POST":
        # 사용자의 요청 정보를 담아준다.
        form = MusicianForm(request.POST)
        # forms를 상속받았기 때문에 사용가능
        if form.is_valid():
            # Musician가 models에게 받은 메소드
            # ModelForm을 정의할 때 
            # class Meta : model = Musician을 담아줌
            musician = form.save()
            # redireact('app_name:path_name')
            return redirect('musicians:index')
    else:
        # MusicianForm 불러오기
        # form은 MusicianForm 인스턴스
        # MusicianForm이 가진 정보를 가짐
        # MusicianForm은 Musician wjdqh
        # template에 보여줄 tag들
        form = MusicianForm()
        print(form)

    context ={
        'form':form
    }
    return render(request, 'musicians/create.html', context)

# 함수정의 함수이름 (사용자요청저보, url에 작성한 변수명)
def detail(request, musician_pk):
    # Model.objects.get(조건=변수명)
    musician = Musician.objects.get(pk=musician_pk)
    albums = musician.album_set.all()
    context = {
        'musician' : musician,
        'albums': albums,
    }
    return render(request, 'musicians/detail.html', context)

# update 작성시 주의사항
# instance 값 form에게 담아주기
def update(request, musician_pk):
    musician = Musician.objects.get(pk=musician_pk)
    if request.method == "POST":
        form = MusicianForm(request.POST , instance=musician)
        if form.is_valid():
            musician = form.save()
            return redirect('musicians:index')
    else:
        form = MusicianForm(instance=musician)

    context = {
        'form': form
    }
    return render(request, 'musicians/create.html', context)

def delete(request, musician_pk):
    musician = Musician.objects.get(pk=musician_pk)
    musician.delete()
    return redirect('musicians:index')

def album_create(request, musician_pk):
    return redirect('musicians:detail',)

review/musicians/templates/musicians/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>create</title>
</head>
<body>
  {% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
  {% else %}
  <h1>글 수정</h1>
  {% endif %}
  <hr>
  <!-- action을 비워두면 현재 위치로 요청 -->
  <!-- 차이점 : method를 지정해 줬다. -->
  <!-- a tag : GET방식 -->
  <form action="" method="POST">
    {% csrf_token %}
    <!-- views에서 context에 담아 넘겨준 form -->
    {{form}}
    <input type="submit">
  </form>
  <a href="{% url 'musicians:index' %}">[BACK]</a>
</body>
</html>

review/musicians/templates/musicians/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>상세 페이지</h1>
  <hr>
  <!-- musician은 결국 인스턴스다. -->
  <h1>{{ musician }}</h1>
  <hr>
  <!-- 각 변수에 접근할 수 있다. -->
  <P>이름 : {{ musician.name }}</P>
  <p>나이 : {{ musician.age }}</p>
  <hr>
  <p>{{ albums|length }}개의 앨범</p>
  <ul>
  {% for album in albums %}
    <li>{{ album.title }}</li>
  {% empty %}
    <p>앨범이 없습니다.</p>
  {% endfor %}
</ul>
  <a href="{% url 'musicians:update' musician.pk %}">수정</a>
  <a href="{% url 'musicians:delete' musician.pk %}">삭제</a>
  <a href="{% url 'musicians:index' %}">[back]</a>
</body>
</html>

review/musicians/templates/musicians/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index</title>
</head>
<body>
  <h1>메인 페이지</h1>
  <hr>
  <a href="{%url 'musicians:create' %}">생성</a>
  <ul>
    {% for musician in musicians %}
      <a href="{% url 'musicians:detail' musician.pk %}">
        <li>{{ musician.name }}</li>
      </a>
    {% endfor %}
  </ul>
</body>
</html>